#ifndef LIBFT_API_H
#define LIBFT_API_H

/*
** The tester never calls your libft through the prototypes of your libft.h:
** a missing or wrong prototype would stop the whole build.
**
**  - probe.h (generated by prepare.sh) says what your libft.h declares.
**  - Your libft.h is included with every ft_* renamed to user_ft_*, so its
**    prototypes can be compared with the subject (test_prototypes.c) without
**    ever conflicting with the ones below.
**  - The tester then uses the subject prototypes below. libft_api.c gives
**    each one a weak default: yours replace them at link time, and a
**    function you don't have yet is reported as [MISSING] instead of a link
**    error (even when another function of your libft calls it).
*/

#include <stddef.h>
#include "probe.h"

#include "rename.h"
#if HAS_LIBFT_H
# include "libft.h"
#endif
#include "unrename.h"

#if !HAS_T_LIST
typedef struct s_tester_list
{
	void					*content;
	struct s_tester_list	*next;
}	t_list;
#endif

int				ft_isalpha(int c);
int				ft_isdigit(int c);
int				ft_isalnum(int c);
int				ft_isascii(int c);
int				ft_isprint(int c);
size_t			ft_strlen(const char *s);
void			*ft_memset(void *s, int c, size_t n);
void			ft_bzero(void *s, size_t n);
void			*ft_memcpy(void *dst, const void *src, size_t n);
void			*ft_memmove(void *dst, const void *src, size_t n);
size_t			ft_strlcpy(char *dst, const char *src, size_t size);
size_t			ft_strlcat(char *dst, const char *src, size_t size);
int				ft_toupper(int c);
int				ft_tolower(int c);
char			*ft_strchr(const char *s, int c);
char			*ft_strrchr(const char *s, int c);
int				ft_strncmp(const char *s1, const char *s2, size_t n);
void			*ft_memchr(const void *s, int c, size_t n);
int				ft_memcmp(const void *s1, const void *s2, size_t n);
char			*ft_strnstr(const char *big, const char *little, size_t len);
int				ft_atoi(const char *nptr);
void			*ft_calloc(size_t nmemb, size_t size);
char			*ft_strdup(const char *s);
char			*ft_substr(char const *s, unsigned int start, size_t len);
char			*ft_strjoin(char const *s1, char const *s2);
char			*ft_strtrim(char const *s1, char const *set);
char			**ft_split(char const *s, char c);
char			*ft_itoa(int n);
char			*ft_strmapi(char const *s, char (*f)(unsigned int, char));
void			ft_striteri(char *s, void (*f)(unsigned int, char *));
void			ft_putchar_fd(char c, int fd);
void			ft_putstr_fd(char *s, int fd);
void			ft_putendl_fd(char *s, int fd);
void			ft_putnbr_fd(int n, int fd);
t_list			*ft_lstnew(void *content);
void			ft_lstadd_front(t_list **lst, t_list *new);
unsigned int	ft_lstsize(t_list *lst);
t_list			*ft_lstlast(t_list *lst);
void			ft_lstadd_back(t_list **lst, t_list *new);
void			ft_lstdelone(t_list *lst, void (*del)(void *));
void			ft_lstclear(t_list **lst, void (*del)(void *));
void			ft_lstiter(t_list *lst, void (*f)(void *));
t_list			*ft_lstmap(t_list *lst, void *(*f)(void *), void (*del)(void *));

#define LIBFT_FUNCS(X) \
	X(ft_isalpha) X(ft_isdigit) X(ft_isalnum) X(ft_isascii) X(ft_isprint) \
	X(ft_strlen) X(ft_memset) X(ft_bzero) X(ft_memcpy) X(ft_memmove) \
	X(ft_strlcpy) X(ft_strlcat) X(ft_toupper) X(ft_tolower) X(ft_strchr) \
	X(ft_strrchr) X(ft_strncmp) X(ft_memchr) X(ft_memcmp) X(ft_strnstr) \
	X(ft_atoi) X(ft_calloc) X(ft_strdup) X(ft_substr) X(ft_strjoin) \
	X(ft_strtrim) X(ft_split) X(ft_itoa) X(ft_strmapi) X(ft_striteri) \
	X(ft_putchar_fd) X(ft_putstr_fd) X(ft_putendl_fd) X(ft_putnbr_fd) \
	X(ft_lstnew) X(ft_lstadd_front) X(ft_lstsize) X(ft_lstlast) \
	X(ft_lstadd_back) X(ft_lstdelone) X(ft_lstclear) X(ft_lstiter) X(ft_lstmap)

/* 1 if the libft function fn is in libft.a; *declared (if not NULL) tells
** whether libft.h declares it (libft_api.c). */
int				t_func_exists(const char *fn, int *declared);

/* Called by the stub of a missing function (framework.c): ends the test
** as [MISSING]. */
void			t_missing_call(const char *fn) __attribute__((noreturn));

#endif
