#!/usr/bin/env bash
# Prepares everything the tester links against, and never stops on an error:
#   1. builds your libft with your Makefile; if it doesn't compile, builds an
#      archive with only the .c files that do compile
#   2. describes your libft.h (probe.h: what is declared, t_list...)
# Details go to the trace file, the screen gets one line per step.

DIR="${1:-..}"
BUILD="${2:-.build}"
TRACE="${3:-traces.log}"
CC="${CC:-cc}"
RED=$'\e[1;31m'; GRN=$'\e[1;32m'; DIM=$'\e[2m'; RST=$'\e[0m'

FUNCS="ft_isalpha ft_isdigit ft_isalnum ft_isascii ft_isprint ft_strlen ft_memset ft_bzero
ft_memcpy ft_memmove ft_strlcpy ft_strlcat ft_toupper ft_tolower ft_strchr ft_strrchr ft_strncmp
ft_memchr ft_memcmp ft_strnstr ft_atoi ft_calloc ft_strdup ft_substr ft_strjoin ft_strtrim
ft_split ft_itoa ft_strmapi ft_striteri ft_putchar_fd ft_putstr_fd ft_putendl_fd ft_putnbr_fd
ft_lstnew ft_lstadd_front ft_lstsize ft_lstlast ft_lstadd_back ft_lstdelone ft_lstclear
ft_lstiter ft_lstmap"

mkdir -p "$BUILD"

line() { printf "  %-70s %s\n" "$1" "$2"; }
trace() { printf "%s\n" "$@" >> "$TRACE"; }
# write stdin to $1 only if it changed, so nothing is recompiled for nothing
update() { cat > "$1.tmp"; if cmp -s "$1.tmp" "$1"; then rm -f "$1.tmp"; else mv "$1.tmp" "$1"; fi; }

# ------------------------------------------------------------------ libft.a
trace "" "==================== BUILD: your libft ====================" ""
if make -C "$DIR" --no-print-directory >> "$TRACE" 2>&1 && [ -f "$DIR/libft.a" ]; then
	update "$BUILD/libft.a" < "$DIR/libft.a"
	line "build your libft (make)" "${GRN}[OK]${RST}"
else
	trace "" "-> make failed: compiling every .c on its own, only the ones that compile are tested" ""
	rm -rf "$BUILD/objs"
	mkdir -p "$BUILD/objs"
	bad=""
	for f in "$DIR"/*.c; do
		[ -e "$f" ] || continue
		o="$BUILD/objs/$(basename "${f%.c}").o"
		$CC -Wall -Wextra -c "$f" -I"$DIR" -o "$o" >> "$TRACE" 2>&1 || bad="$bad $(basename "$f")"
	done
	rm -f "$BUILD/partial.a"
	ar rcs "$BUILD/partial.a" $(ls "$BUILD"/objs/*.o 2>/dev/null) >> "$TRACE" 2>&1
	update "$BUILD/libft.a" < "$BUILD/partial.a"
	[ -n "$bad" ] && trace "" "-> these files do not compile:$bad"
	line "build your libft (make)" "${RED}[KO]${RST} ${DIM}see traces${RST}"
fi

# ------------------------------------------------------------------ libft.h
trace "" "==================== BUILD: your libft.h ====================" ""
for f in $FUNCS; do echo "#define $f user_$f"; done | update "$BUILD/rename.h"
for f in $FUNCS; do echo "#undef $f"; done | update "$BUILD/unrename.h"

has_h=0
has_list=0
errs=""
src="$BUILD/probe.c"
if [ ! -f "$DIR/libft.h" ]; then
	trace "-> libft.h not found in $DIR"
	line "libft.h" "${RED}[KO]${RST} ${DIM}not found${RST}"
else
	printf '#include "rename.h"\n#include "libft.h"\n' > "$src"
	if $CC -fsyntax-only -I"$BUILD" -I"$DIR" "$src" >> "$TRACE" 2>&1; then
		has_h=1
		{
			printf '#include "rename.h"\n#include "libft.h"\nvoid\tprobe(void)\n{\n'
			for f in $FUNCS; do echo "(void)&user_$f;"; done
			printf '(void)sizeof(t_list);\n}\n'
		} > "$src"
		# only the identifiers reported as undeclared (gcc and clang wording),
		# not the "did you mean ..." suggestions next to them
		errs=$($CC -fsyntax-only -I"$BUILD" -I"$DIR" "$src" 2>&1 | sed -n \
			-e 's/.*undeclared identifier [^a-zA-Z_]*\([a-zA-Z_]*\).*/\1/p' \
			-e 's/.*unknown type name [^a-zA-Z_]*\([a-zA-Z_]*\).*/\1/p' \
			-e 's/^[^ ]* error: [^a-zA-Z_]*\([a-zA-Z_]*\)[^a-zA-Z_ ]* undeclared.*/\1/p')
		echo "$errs" | grep -qx 't_list' || has_list=1
		line "libft.h" "${GRN}[OK]${RST}"
	else
		trace "-> libft.h does not compile (errors above): tested as if it declared nothing"
		line "libft.h" "${RED}[KO]${RST} ${DIM}does not compile, see traces${RST}"
	fi
fi

{
	echo "/* generated by prepare.sh from $DIR/libft.h */"
	echo "#define HAS_LIBFT_H $has_h"
	echo "#define HAS_T_LIST $has_list"
	for f in $FUNCS; do
		if [ $has_h = 1 ] && ! echo "$errs" | grep -qx "user_$f"; then
			echo "#define DECL_$f 1"
			echo "#define CHK_$f(t) __builtin_types_compatible_p(__typeof__(&user_$f), t)"
		else
			echo "#define DECL_$f 0"
			echo "#define CHK_$f(t) (-1)"
		fi
	done
} | update "$BUILD/probe.h"
rm -f "$src"
exit 0
